### ISSUE TITLE
"Build Ansible docker" images worflow should run on merge on main branch

### ISSUE THREAD

**Issue by pierreboissinot** [le-phare/ansible-deploy#38]
I can't use recent changes on main branch because "Build Ansible docker" workflow is scheduled.

The docker image lephare/ansible-deploy should on merge event.

**Comment by pierreboissinot** [comment]
We may tag a version 1.8.2 ?

**Comment by thislg** [comment]
There is a new feature so it should be 1.9.0. We need to update the changelog then pushing the tag should build a new image.

**Comment by aegypius** [comment]
If you want I can setup the same type of release process (using release please) as I have done in some internal projects. Create an issue and assign me if you are interested!

**Comment by thislg** [comment]
Thank you @aegypius

**Comment by thislg** [comment]
I tagged 1.9.0.
