### ISSUE TITLE
.bashrc

### ISSUE THREAD

**Issue by pierreboissinot** [le-phare/ansible-deploy#8]
Aujourd'hui les .bashrc sur les machines ne satisfont personne, du coup chacun écrit son .bashrc à la main.
Le deploy pourrait envoyer un ou plusieurs `.bashrc` dans un dossier `~/.bashrc.d`:
----`~/`
--------`.bashrc.d/`
------------`.bashrc` (commun à tout projet utilisant lephare/ansible-deploy)
------------`.projetrc` (optionnel, spécifique au projet)
Où le `~/.bashrc` source tout fichier se trouvant dans le répertoire `~/.bashrc.d`

Il faudrait se mettre d'accord sur un .bashrc commun. A partir de ceux que nous avons l'habitude d'utiliser on a de quoi faire cc @Athalyan @jacbac

Extrait d'une discussion avec @erichard

**Comment by erichard** [comment]
il vaudrait mieux renommer le `.bashrc.d/.bashrc` pour évitez des confusions. `.bashrc.d/common.bashrc` par exemple ?

**Comment by aegypius** [comment]
Je suis assez d'accord, mieux encore il faudrait numéroter les fichiers contrôler l'ordre de source par exemple: 

```
~/.bashrc.d/
    00-common.bashrc
```
